[env:seeed_wio_terminal]
platform = atmelsam
board = seeed_wio_terminal
framework = arduino
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DLCD_BACKLIGHT=72
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
    seeed-studio/Seeed Arduino FS@^2.1.1
    seeed-studio/Seeed Arduino SFUD@^2.0.2
    seeed-studio/Seeed Arduino rpcUnified@^2.1.4
    seeed-studio/Seeed_Arduino_mbedtls@^3.0.1
    seeed-studio/Seeed Arduino rpcBLE@^1.0.0
    seeed-studio/Seeed_Arduino_LCD@^1.6.0

[env:native]
platform = native
test_framework = unity
build_flags =
    -std=gnu++17
    -I src
lib_deps =
    bblanchon/ArduinoJson@^6.21.5
